#!/bin/sh
# This is developed by laojifuli to un-pack my option by using tinycore

# This tool will un-pack the linux filesystem cpio from archived gzip or lzma format

getLast() {
    FILE_TYPE=$(echo $1 | cut -d'.' -f 2-)    
    if [ "$FILE_TYPE" != "$1" ]; then
        getLast "$FILE_TYPE"
    fi
}

if [ $(whoami) != "root" ] && [ $(whoami) != "admin" ]; then
    echo "Switch to root and please try again"
    sudo su
    exit 1
fi

#help screen
if  [ $# != 1 ]; then
echo "
Usage: unpacking archived_image(.gz or .lzma)

example:
    ./unpacking laojifuli.gz
"
exit 1
fi

FILE_NAME=$(echo $1 | cut -d'.' -f1)
getLast $1
if [ "$FILE_TYPE" != "gz" ] && [ "$FILE_TYPE" != "lzma" ]; then
    echo "Could not unpacking the image of $1"
    exit 1
fi

if [ ! -d ./$FILE_NAME ]; then
    echo "The $FILE_NAME directory did not exist. Create it for unpacking."
    mkdir $FILE_NAME
else
    rm -rf $FILE_NAME/*
fi

WORKING_DIR=$(pwd)

echo "Un-packing the $1. Please wait a while."
cd $FILE_NAME
if [ "$FILE_TYPE" == "gz" ]; then
    gzip -dc ../$1 | cpio -id
else
    lzma -dc ../$1 | cpio -id
fi

cd ${WORKING_DIR}

echo "Un-packing the $1 successful."
echo
exit 0
