#!/usr/bin/env bash

sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
mkdir output
curl -sL api.github.com/repos/hong0980/chinternet/releases | awk -F'"' '/browser_download_url/{print $4}' | grep 'cache' > xc
curl -sL api.github.com/repos/hong0980/Actions-OpenWrt/releases | awk -F'"' '/browser_download_url/{print $4}' | grep 'cache' > xx

while read -r line; do
    if ! grep -q "${line##*/}" xc 2>/dev/null; then
        if wget -qO "output/${line##*/}" "$line"; then
            if [[ $(du -m "output/${line##*/}" | cut -f1) -ge 100 ]]; then
                echo "${line##*/} 已经下载完成"
            else
                rm -f "output/${line##*/}"
            fi
        fi
    fi
done < xx

if [ "$(ls -A output)" ]; then
    echo "UPLOAD_Release=true" >>$GITHUB_ENV
else
    echo "没有新的cache可以下载！"
fi
