#!/usr/bin/env bash

## 本脚本搬运并模仿 liuqitoday
. /ql/shell/share.sh
code_shell_path=$dir_config/code.sh
# 获取token
token=$(cat $file_auth_user | jq --raw-output .token)
sed -i "s|By：https://github.com/whyour/qinglong|By：qinglong|" $file_notify_js

# 下载 config.sh
[[ -e $file_config_user ]] || echo "" >$file_config_user
if [[ "$(grep -c 'JD_UNSEB_NOTIFY' $file_config_user)" == "0" ]]; then
	[[ -s $file_config_user ]] && mv $file_config_user $dir_config/config.sh.bk
	if wget -O $file_config_user https://ghproxy.com/https://raw.githubusercontent.com/Oreomeow/VIP/main/Conf/Qinglong/config.sample.sh; then
		sed -i 's/FRUIT_BEAN_CARD.*/FRUIT_BEAN_CARD="false"/' $file_config_user
	else
		echo "config.sh 下载失败"
		exit 0
	fi
fi

# 下载 extra.sh
[[ -e $file_extra_shell ]] || echo "" >$file_extra_shell
if [[ "$(grep -c 'package_name' $file_extra_shell)" == "0" ]]; then
	[[ -s $file_extra_shell ]] && mv $file_extra_shell $dir_config/extra.sh.bk
	if wget -O $file_extra_shell https://ghproxy.com/https://raw.githubusercontent.com/Oreomeow/VIP/main/Tasks/qlrepo/extra.sh; then
		chmod +x $file_extra_shell
	else
		echo "extra.sh 下载失败"
		exit 0
	fi
fi

# 将 extra.sh 添加到定时任务
if [[ "$(grep -c extra $list_crontab_user)" == "0" ]]; then
	echo "开始添加 extra"
	curl -s -H 'Accept: application/json' -H "Authorization: Bearer $token" -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept-Language: zh-CN,zh;q=0.9' --data-binary '{"name":"初始化任务","command":"ql extra","schedule":"15 0-23/4 * * *"}' --compressed 'http://127.0.0.1:5700/api/crons?t=1624782068473' 1>/dev/null 2>&1
fi

# 将 wskey 添加到定时任务
if [[ "$(grep -c wskey $list_crontab_user)" == "0" ]]; then
	echo "开始添加 wskey"
	curl -s -H 'Accept: application/json' -H "Authorization: Bearer $token" -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept-Language: zh-CN,zh;q=0.9' --data-binary '{"name":"拉取wskey","command":"ql repo https://github.com/Zy143L/wskey.git \"wskey\"","schedule":"20 */3 * * *"}' --compressed 'http://127.0.0.1:5700/api/crons?t=1624782068473' 1>/dev/null 2>&1
fi

# 将 diy 添加到定时任务
if [[ "$(grep -c diy $list_crontab_user)" == "0" ]]; then
	echo "开始添加 diy"
	curl -s -H 'Accept: application/json' -H "Authorization: Bearer $token" -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept-Language: zh-CN,zh;q=0.9' --data-binary '{"name":"运行diy.sh","command":"ql diy","schedule":"0 5 */15 * *"}' --compressed 'http://127.0.0.1:5700/api/crons?t=1624782068473' 1>/dev/null 2>&1
fi

# 将 bot 添加到定时任务
if [[ "$(grep -c bot $list_crontab_user)" == "0" ]]; then
	echo "开始添加 bot"
	curl -s -H 'Accept: application/json' -H "Authorization: Bearer $token" -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept-Language: zh-CN,zh;q=0.9' --data-binary '{"name":"拉取机器人","command":"ql bot","schedule":"13 14 * * *"}' --compressed 'http://127.0.0.1:5700/api/crons?t=1626247933219' 1>/dev/null 2>&1
fi

# extra.sh 预设仓库及默认拉取仓库设置
echo -e "\n（2）JDHelloWorld	https://github.com/JDHelloWorld/jd_scripts\n（3）he1pu		https://github.com/he1pu/JDHelp\n（4）shufflewzc		https://github.com/shufflewzc/faker2\n（6）Aaron-lv		https://github.com/Aaron-lv/sync\n（7）yuannian1112	https://github.com/yuannian1112/jd_scripts\n"
echo -n "输入你想拉取的仓库编号，多个仓库用空格(默认为 4):"
read -r defaultNum
defaultNum=${defaultNum:-'4'}
sed -i "s/^CollectedRepo.*/CollectedRepo=($defaultNum) ##示例：CollectedRepo=(2 4 6)/g" $file_extra_shell

## 下载 code.sh
# [[ -e $code_shell_path ]] || echo "" >$code_shell_path
# if [[ "$(grep -c 'shufflewzc_faker2' $code_shell_path)" == "0" ]]; then
	# [[ -s $code_shell_path ]] && mv $code_shell_path $dir_config/code.sh.bk
	# if wget -O $code_shell_path https://ghproxy.com/https://raw.githubusercontent.com/Oreomeow/VIP/main/Scripts/sh/Helpcode2.8/code.sh; then
		# chmod +x $code_shell_path
		# sed -i 's/$repo4/$repo/' $code_shell_path
	# else
		# echo "code.sh 下载失败"
		# exit 0
	# fi
# fi

## code.sh 预设仓库及默认调用仓库设置
# echo -e "\n## 将\"repo=\$repo1\"改成\"repo=\$repo2\"或其他，以默认调用其他仓库脚本日志\nrepo2='JDHelloWorld_jd_scripts'		#预设的 JDHelloWorld 仓库\nrepo3='he1pu_JDHelp'			#预设的 he1pu 仓库\nrepo4='shufflewzc_faker2'		#预设的 shufflewzc 仓库\nrepo6='Aaron-lv_sync_jd_scripts'	#预设的 Aaron-lv 仓库\nrepo7='yuannian1112_jd_scripts'		#预设的 yuannian1112 仓库\nrepo=\$repo4				#默认调用 shufflewzc_faker2 仓库脚本日志\n"
# echo -n "输入你想调用的仓库编号(默认为 4):"
# read -r repoNum
# repoNum=${repoNum:-'4'}
# sed -i "s/repo=.*/repo=\$repo$repoNum/g" $code_shell_path

## 将 code.sh 添加到定时任务
# if [[ "$(grep -c 'code.sh' $list_crontab_user)" == "0" ]]; then
	# echo "开始添加 task code.sh"
	# curl -s -H 'Accept: application/json' -H "Authorization: Bearer $token" -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept-Language: zh-CN,zh;q=0.9' --data-binary '{"name":"格式化更新助力码","command":"bash /ql/config/code.sh &","schedule":"*/10 * * * *"}' --compressed 'http://127.0.0.1:5700/api/crons?t=1626247939659' 1>/dev/null 2>&1
# fi

# 下载 task_before.sh
if ! wget -O $file_task_before https://ghproxy.com/https://raw.githubusercontent.com/Oreomeow/VIP/main/Scripts/sh/Helpcode2.8/task_before.sh; then
	echo "task_before.sh 下载失败"
	exit 0
fi

[[ "$(grep -c 'diy.sh' $dir_shell/update.sh)" == "0" ]] && \
sed -i '/update_qinglong "$2"/a\        [[ -f $dir_config/diy.sh ]] && . $dir_config/diy.sh >>$log_path\n        ;;\n     diy)\n        if [[ ${EnableExtraShell} == true ]] && [[ -f $dir_config/diy.sh ]]; then\n        echo -e "## 开始执行... $begin_time\\n" >>$log_path\n        [[ -f $task_error_log_path ]] && cat $task_error_log_path >>$log_path\n            . $dir_config/diy.sh >>$log_path\n        fi' $dir_shell/update.sh

if [[ ! -s $dir_config/diy.sh ]]; then
	cat >"$dir_config/diy.sh" <<-\EOF
		#!/usr/bin/env bash
		echo "运行diy脚本"
		. /ql/shell/share.sh
		[[ "`grep -c 'diy.sh' $dir_shell/update.sh`" == "0" ]] && \
		sed -i '/update_qinglong "$2"/a\        [[ -f $dir_config/diy.sh ]] && . $dir_config/diy.sh >>$log_path\n        ;;\n     diy)\n        if [[ ${EnableExtraShell} == true ]] && [[ -f $dir_config/diy.sh ]]; then\n        echo -e "## 开始执行... $begin_time\\n" >>$log_path\n        [[ -f $task_error_log_path ]] && cat $task_error_log_path >>$log_path\n            . $dir_config/diy.sh >>$log_path\n        fi' $dir_shell/update.sh
		
		sed -i "s|By：https://github.com/whyour/qinglong|By：qinglong|" $file_notify_js
	EOF
fi
