#!/bin/sh

. "$IPKG_INSTROOT/usr/share/libubox/jshn.sh"
action=$1
shift

case "$action" in
	cat)
		case "$1" in
			conf)
				config_dir="/etc/config/qbittorrent"
			;;
			qBittorrent)
				config_dir="$(uci -q get qbittorrent.main.RootProfilePath)/qBittorrent/config/qBittorrent.conf"
			;;
		esac
		json_init
		json_add_string file "$config_dir"
		json_add_string content "$(cat "$config_dir")"
		json_dump
	;;
	tail)
		log_file="$(uci -q get qbittorrent.main.Path)/qbittorrent.log" || \
		log_file="$(uci -q get qbittorrent.main.RootProfilePath)/qBittorrent/data/logs/qbittorrent.log"
		tail -n 50 "$log_file"
	;;
esac
